baseURL = 'https://gallery.fanello.net/'
languageCode = 'en-us'
title = 'Fanello Family Photo Gallery'
theme = 'gallery'
timeout = '60m'
copyright = 'Copyright 2014-2025 - Adam and Diana Fanello'
timeZone = 'America/Los_Angeles'

[Params]
defaultTheme = 'dark'
